#!/bin/bash

sysctl -p

iptables -t nat -A POSTROUTING -j MASQUERADE
iptables-save

if [ -n "$CONTAINER_GATEWAY" ] ; then
  GATEWAY_IP=`getent hosts $CONTAINER_GATEWAY | awk '{print $1}'`

  if [ -n "$GATEWAY_IP" ] ; then
    ip route flush 11
    ip route add table 11 to default via $GATEWAY_IP dev eth0
    ip rule add from 10.8.0.0/24 table 11 priority 11
  else
    echo "ERROR: VPN gateway $CONTAINER_GATEWAY not found"
    exit 1
  fi
else
  echo "WARNING: no VPN gateway provided, routing directly to the internet."
fi

if [ ! -e "/dev/net/tun" ] ; then
   mkdir /dev/net
   mknod /dev/net/tun c 10 200
fi;

exec openvpn /etc/openvpn/server.conf

